version: 2

sources:
  - name: ecommerce_data 
    schema: Nov_star_sample   # The name of BigQuery Dataset
    tables:
      - name: fact_events 
      - name: dim_date
      - name: dim_product
      - name: dim_user
      - name: dim_event_type
      - name: dim_session
      