default:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: digital-analytics-464705  # Your GCP project ID
      dataset: dbt_aezzari  # Target dataset for dbt models (different from source)
      threads: 4
      timeout_seconds: 300
      location: africa-south1
      priority: interactive
      keyfile: /opt/airflow/dbt-user-creds.json  # Path to service account JSON in container
      
    prod:
      type: bigquery
      method: service-account
      project: digital-analytics-464705  # Your GCP project ID
      dataset: dbt_aezzari_prod
      threads: 8
      timeout_seconds: 300
      location: africa-south1
      priority: batch
      keyfile: /opt/airflow/dbt-user-creds.json 